version: '3.7'
services:
  database:
    image: postgres:11-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: autodeploy
volumes:
  dbdata: